In [33]:
import pandas as pd

In [ ]:
df=pd.read_csv("csvfile/Luxury_Housing_Bangalore.csv") # load the dataset from csv file into dataframe

In [35]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,â‚¹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [ ]:
df.describe() # generates statistics for numeric columns(helps to understand distribution and spread of data)

,Unit_Size_Sqft,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90954.000000,101000.000000,90910.000000,101000.000000,101000.000000
mean,5972.274765,6.992619,7.503663,7.498426,67.182921
std,1783.397836,1.731757,1.440758,1.443128,30.271611
min,-1.000000,4.000031,5.000224,5.000013,15.000000
25%,4477.250000,5.494526,6.260329,6.247954,41.000000
50%,5990.000000,6.985805,7.499123,7.495614,67.000000
75%,7497.000000,8.490000,8.752207,8.749824,93.000000
max,8999.000000,9.999970,9.999865,9.999956,119.000000

In [ ]:
df.info() # basic info abt the df includes no:of:entries,column names,non-null counts and data types.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [ ]:
df.isnull() # check for missing values in df | returns true- missing values//false-present values

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
100999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()  # counts total no:of missing values in each column of  df

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [ ]:
df.duplicated() # checks for duplicate rows if true-row is a duplicate / if false row is unique

0         False
1         False
2         False
3         False
4         False
          ...
100995     True
100996     True
100997     True
100998     True
100999     True
Length: 101000, dtype: bool

In [ ]:
df.duplicated().sum() # Count the total number of duplicate rows in the df

np.int64(1000)

In [ ]:
df.drop_duplicates(inplace=True) # Remove all duplicate rows from  df and update it in place

In [ ]:
df.sample(10) # Randomly sample 10 rows from df for inspection

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
83920,PROP083921,SARJAPUR ROAD,Project_420,Total Environment,8407.0,4Bhk,9.611480232393408,Secondary,HNI,2023-09-30,9.472347,7.056104,Under construction,NRI Desk,no,8.954222,108,Great view from 15th floor.
93128,PROP093129,SARJAPUR ROAD,Project_128,RMZ,5169.0,5bhk+,10.85778210720651,Secondary,Startup Founder,2024-09-30,7.066335,7.957074,Ready to move,Online,no,7.291024,38,Loved the amenities!
89086,PROP089087,Hennur Road,Project_86,Brigade,5178.0,5BHK+,â‚¹5.32 Cr,Secondary,HNI,2023-06-30,7.773982,8.192930,Launch,NRI Desk,yes,6.783045,96,Excellent location!
11362,PROP011363,MG ROAD,Project_362,Embassy,5683.0,3Bhk,9.172954038493996,Primary,HNI,2023-09-30,9.264002,9.242857,Launch,NRI Desk,yes,6.325536,23,Will buy after possession.
37667,PROP037668,whitefield,Project_167,Puravankara,NaN,5bhk+,â‚¹8.44 Cr,Secondary,HNI,2023-06-30,6.491816,5.483914,Ready to move,NRI Desk,no,6.443312,116,Agent was not responsive.
57177,PROP057178,domlur,Project_177,Godrej,8548.0,4bhk,13.1268513078758,Primary,HNI,2023-09-30,7.310949,9.191257,Under construction,Broker,no,6.501554,19,Will buy after possession.
411,PROP000412,Electronic City,Project_411,Puravankara,7285.0,3bhk,7.373730252336553,Secondary,Other,2025-03-31,8.060437,5.305028,Under construction,Online,yes,7.759782,40,Excellent location!
55255,PROP055256,Bannerghatta Road,Project_255,Prestige,6725.0,5BHK+,â‚¹7.39 Cr,Secondary,Startup Founder,2024-06-30,6.906424,9.190122,Launch,NRI Desk,yes,9.676214,115,NaN
45977,PROP045978,HEBBAL,Project_477,Brigade,5534.0,5Bhk+,â‚¹12.52 Cr,Primary,NRI,2023-06-30,9.681779,8.651093,Under construction,Broker,no,7.844919,102,Great value for money.
72364,PROP072365,JP NAGAR,Project_364,SNN Raj,8100.0,5BHK+,14.406573350453783,Primary,NRI,2024-09-30,9.126330,7.684991,Ready to move,Broker,yes,6.249981,105,Agent was not responsive.

In [ ]:
df['Ticket_Price_Cr']=df['Ticket_Price_Cr'].str.replace('Cr','',regex=False).str.strip().str.replace('Rs','').str.replace('â‚¹','')
# Clean the 'Ticket_Price_Cr' column by removing unwanted characters like 'Cr', 'Rs', and 'â‚¹', and then strip extra spaces
df['Ticket_Price_Cr']=pd.to_numeric(df['Ticket_Price_Cr'],errors='coerce')
# Convert the cleaned 'Ticket_Price_Cr' column to numeric values; invalid parsing will be set as NaN

In [ ]:
df['Ticket_Price_Cr'] # Display the cleaned and converted 'Ticket_Price_Cr' column to verify the changes

0        12.750846
1        16.292152
2        10.517724
3         9.396367
4        15.345392
           ...
99995    10.185193
99996    12.272081
99997    13.730179
99998    10.363989
99999    10.415617
Name: Ticket_Price_Cr, Length: 100000, dtype: float64

In [ ]:
df['Unit_Size_Sqft'] = df['Unit_Size_Sqft'].fillna(df['Unit_Size_Sqft'].mean())
# Fill missing values in 'Unit_Size_Sqft' with the mean of the column
df['Ticket_Price_Cr'] = df['Ticket_Price_Cr'].fillna(df['Ticket_Price_Cr'].mean())
# Fill missing values in 'Ticket_Price_Cr' with the mean of the column
df['Amenity_Score'] = df['Amenity_Score'].fillna(df['Amenity_Score'].median())
# Fill missing values in 'Amenity_Score' with the median of the column
df['Buyer_Comments'] = df['Buyer_Comments'].fillna("No Comments")
# Fill missing values in 'Buyer_Comments' with the placeholder text "No Comments"

In [48]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under construction,NRI Desk,no,7.723898,106,No Comments
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,bellary road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,8.379908,7.499766,Under construction,Online,yes,8.378800,109,Underpriced for location.
99996,PROP099997,YELAHANKA,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.
99997,PROP099998,rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,NRI Desk,yes,8.984990,63,No Comments
99998,PROP099999,INDIRANAGAR,Project_498,SNN Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,9.435646,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Comments
99999,PROP100000,hennur road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,yes,6.039943,95,No Comments

In [49]:
df.dtypes

Property_ID              object
Micro_Market             object
Project_Name             object
Developer_Name           object
Unit_Size_Sqft          float64
Configuration            object
Ticket_Price_Cr         float64
Transaction_Type         object
Buyer_Type               object
Purchase_Quarter         object
Connectivity_Score      float64
Amenity_Score           float64
Possession_Status        object
Sales_Channel            object
NRI_Buyer                object
Locality_Infra_Score    float64
Avg_Traffic_Time_Min      int64
Buyer_Comments           object
dtype: object

In [ ]:
# normalize text columns(list of columns containing text data )
norm_column = ['Micro_Market', 'Developer_Name', 'Configuration',
             'Transaction_Type', 'Buyer_Type', 'Possession_Status',
             'Sales_Channel', 'NRI_Buyer']

In [ ]:
# for loop through each column in the list of text columns
for col in norm_column:
    df[col]=df[col].str.strip().str.title()
# remove spaces and convert text to title case

In [ ]:
# Calculate price per square foot by converting 'Ticket_Price_Cr' from crores to base currency
# and dividing it by 'Unit_Size_Sqft'
df["Price_per_Sqft"] = df["Ticket_Price_Cr"] * 10000000 / df["Unit_Size_Sqft"]

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  object
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Price_per_Sqft        100000 non-null  float64
dtypes: float64(6), int64(1), object(12)
memory usage: 15.3+ MB

In [54]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4Bhk,12.750846,Primary,Nri,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.120594
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under Construction,Nri Desk,No,7.723898,106,No Comments,28284.985887
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4Bhk,10.517724,Primary,Hni,2023-12-31,8.131315,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.976013
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3Bhk,9.396367,Primary,Hni,2024-03-31,7.501657,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!,15175.012103
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,Hni,2024-12-31,4.525216,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.,21471.096187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,Nri,2023-12-31,8.379908,7.499766,Under Construction,Online,Yes,8.378800,109,Underpriced for location.,18351.699990
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,Yes,7.025209,20,Great view from 15th floor.,38700.980123
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4Bhk,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,Nri Desk,Yes,8.984990,63,No Comments,24522.555158
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4Bhk,10.363989,Primary,Nri,2024-09-30,9.435646,6.369276,Under Construction,Nri Desk,Yes,7.634717,89,No Comments,14116.029667
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,Yes,6.039943,95,No Comments,20764.786348

In [ ]:
# Convert the 'Purchase_Quarter' column to datetime format for easier date manipulation
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])
# Extract the quarter (1 to 4) from the 'Purchase_Quarter' datetime column and store it in 'Quarter_Number'
df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter
# Display the 'Quarter_Number' column to confirm the extracted quarter values
df['Quarter_Number']

0        1
1        2
2        4
3        1
4        4
        ..
99995    4
99996    4
99997    3
99998    3
99999    3
Name: Quarter_Number, Length: 100000, dtype: int32

In [ ]:
df['Purchase_Quarter'].unique() # Display all unique values in the 'Purchase_Quarter' column to understand the range of dates

<DatetimeArray>
['2025-03-31 00:00:00', '2024-06-30 00:00:00', '2023-12-31 00:00:00',
 '2024-03-31 00:00:00', '2024-12-31 00:00:00', '2023-09-30 00:00:00',
 '2024-09-30 00:00:00', '2023-06-30 00:00:00']
Length: 8, dtype: datetime64[ns]

In [57]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4Bhk,12.750846,Primary,Nri,2025-03-31,7.990091,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.120594,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,4.839024,7.499766,Under Construction,Nri Desk,No,7.723898,106,No Comments,28284.985887,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4Bhk,10.517724,Primary,Hni,2023-12-31,8.131315,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.976013,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3Bhk,9.396367,Primary,Hni,2024-03-31,7.501657,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!,15175.012103,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,Hni,2024-12-31,4.525216,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.,21471.096187,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,Nri,2023-12-31,8.379908,7.499766,Under Construction,Online,Yes,8.378800,109,Underpriced for location.,18351.699990,4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,4.716304,6.374069,Launch,Broker,Yes,7.025209,20,Great view from 15th floor.,38700.980123,4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4Bhk,13.730179,Primary,Startup Founder,2023-09-30,6.193347,7.482473,Launch,Nri Desk,Yes,8.984990,63,No Comments,24522.555158,3
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4Bhk,10.363989,Primary,Nri,2024-09-30,9.435646,6.369276,Under Construction,Nri Desk,Yes,7.634717,89,No Comments,14116.029667,3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,5.786292,5.284026,Launch,Broker,Yes,6.039943,95,No Comments,20764.786348,3

In [ ]:
df['Transaction_Type'].unique() # Display all unique values in the 'Transaction_Type' column to understand the different types of transactions

array(['Primary', 'Secondary'], dtype=object)

In [ ]:
df['Booking_Flag'] = df['Transaction_Type'].str.lower().map({'primary': 1, 'secondary': 0}) 
# Create a new column 'Booking_Flag' by mapping 'Transaction_Type' values to binary:
# Convert 'Transaction_Type' to lowercase and map 'primary' to 1 and 'secondary' to 0

In [ ]:
df['Booking_Flag'] # Display the 'Booking_Flag' column to verify that the mapping has been applied correctly

0        1
1        1
2        1
3        1
4        0
        ..
99995    1
99996    0
99997    1
99998    1
99999    1
Name: Booking_Flag, Length: 100000, dtype: int64

In [ ]:
df.rename(columns={"Developer_Name": "Builder"}, inplace=True) 
# Rename the column 'Developer_Name' to 'Builder' for better clarity or standardization
# Use inplace=True to apply the change directly to the dataframe without creating a new one

In [64]:
df

,Property_ID,Micro_Market,Project_Name,Builder,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,Sarjapur Road,Project_0,Rmz,4025.0,4Bhk,12.750846,Primary,Nri,2025-03-31,...,5.462863,Launch,Broker,Yes,9.212491,18,Loved the amenities!,31679.120594,1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.499766,Under Construction,Nri Desk,No,7.723898,106,No Comments,28284.985887,2,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4Bhk,10.517724,Primary,Hni,2023-12-31,...,8.669227,Ready To Move,Direct,Yes,6.985493,113,Agent was not responsive.,13646.976013,4,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3Bhk,9.396367,Primary,Hni,2024-03-31,...,5.720246,Ready To Move,Online,Yes,6.100929,106,Excellent location!,15175.012103,1,1
4,PROP000005,Koramangala,Project_4,Snn Raj,7147.0,4Bhk,15.345392,Secondary,Hni,2024-12-31,...,8.609649,Under Construction,Broker,No,5.312510,18,Too far from my office.,21471.096187,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,Nri,2023-12-31,...,7.499766,Under Construction,Online,Yes,8.378800,109,Underpriced for location.,18351.699990,4,1
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,Yes,7.025209,20,Great view from 15th floor.,38700.980123,4,0
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4Bhk,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,Nri Desk,Yes,8.984990,63,No Comments,24522.555158,3,1
99998,PROP099999,Indiranagar,Project_498,Snn Raj,7342.0,4Bhk,10.363989,Primary,Nri,2024-09-30,...,6.369276,Under Construction,Nri Desk,Yes,7.634717,89,No Comments,14116.029667,3,1
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,Yes,6.039943,95,No Comments,20764.786348,3,1

In [65]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Builder',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments', 'Price_per_Sqft',
       'Quarter_Number', 'Booking_Flag'],
      dtype='object')

In [66]:
!pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\docto\onedrive\desktop\phpay prjct\gh clo extrct\.venv\lib\site-packages (from SQLAlchemy) (4.14.1)
Downloading sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 12.5 MB/s eta 0:00:00
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: greenlet, SQLAlchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   ---------------------------------------- 2/2 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.43 greenlet-3.2.4

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\docto\OneDrive\Desktop\phpay prjct\gh clo extrct\.venv\Scripts\python.exe -m pip install --upgrade pip

In [67]:
!pip install PyMySQL

Collecting PyMySQL
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.1.2

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\docto\OneDrive\Desktop\phpay prjct\gh clo extrct\.venv\Scripts\python.exe -m pip install --upgrade pip

In [69]:
import sys
!{sys.executable} -m pip install SQLAlchemy

Collecting SQLAlchemy
  Using cached sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in x:\guviprojects\luxhouse\.venv\lib\site-packages (from SQLAlchemy) (4.14.1)
Using cached sqlalchemy-2.0.43-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: greenlet, SQLAlchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   ---------------------------------------- 2/2 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.43 greenlet-3.2.4

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [71]:
import sys
!{sys.executable} -m pip install PyMySQL

Collecting PyMySQL
  Using cached pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.1.2

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
"""from sqlalchemy import create_engine

host = "localhost",
user = "root",
port = "3306",
database = "luxhouse_db",
password = "kaasiirajann"

# Create engine
engine = create_engine("mysql+pymysql://root:kaasiirajann@localhost:3306/luxhouse_db")"""

In [ ]:
# df.to_sql("luxury_housing", engine, if_exists="replace", index=False)

100000